#!/usr/bin/env bash

set -e
set -o pipefail
set -x

if [ "$#" -ne 1 ]; then
    echo "Missing argument"
    exit 1
fi

SOURCE=$HOME/llvm-project
INSTALL=$HOME/llvm-build/llvm

cd $SOURCE
UPDATE_CC_TEST_CHECKS="$SOURCE/llvm/utils/update_cc_test_checks.py --llvm-bin=$INSTALL/bin/ "

echo "Regen called on $1"
TESTCASE="$SOURCE/clang/test/$1"
echo "Test case $TESTCASE"

if $(grep -Fq 'Assertions have been autogenerated by utils' "$TESTCASE")
then
   echo "Found assertions string"
else
    echo "Unrecognised header"
    exit 1
fi

if $(grep -Fqx '// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py' "$TESTCASE")
then
    echo "Looks like update_cc_test_checks"
    $UPDATE_CC_TEST_CHECKS $TESTCASE
    exit $?
fi

if $(grep -Fqx '// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5' "$TESTCASE")
then
    echo "Looks like update_cc_test_checks version 5"
    $UPDATE_CC_TEST_CHECKS --version 5 $TESTCASE
    exit $?
fi


echo "Unknown input, ignoring $TESTCASE"

exit

