#!/usr/bin/env bash

set -e
set -o pipefail
set -x

if [ "$#" -ne 1 ]; then
    echo "Missing argument"
    exit 1
fi

SOURCE=$HOME/llvm-project
INSTALL=$HOME/llvm-build/llvm

cd $SOURCE

UPDATE_MIR="$SOURCE/llvm/utils/update_mir_test_checks.py --llc-binary=$INSTALL/bin/llc "

UPDATE_TEST_CHECKS="$SOURCE/llvm/utils/update_test_checks.py --opt-binary=$INSTALL/bin/opt "
UPDATE_TEST_P_CHECKS_GLOBALS="$SOURCE/llvm/utils/update_test_checks.py -p --check-globals --opt-binary=$INSTALL/bin/opt "
UPDATE_TEST_P_CHECKS_FUNCS="$SOURCE/llvm/utils/update_test_checks.py -p --function-signature --opt-binary=$INSTALL/bin/opt "
UPDATE_TEST_CHECKS_FUNCS_GLOBALS="$SOURCE/llvm/utils/update_test_checks.py --function-signature --check-globals --opt-binary=$INSTALL/bin/opt "

UPDATE_TEST_P_CHECKS_ALL_FUNCS="$SOURCE/llvm/utils/update_test_checks.py -p --function-signature --include-generated-funcs --opt-binary=$INSTALL/bin/opt "

UPDATE_LLC_TEST_CHECKS="$SOURCE/llvm/utils/update_llc_test_checks.py --llc-binary=$INSTALL/bin/llc "
UPDATE_LLC_TEST_CHECKS_FORCE="$SOURCE/llvm/utils/update_llc_test_checks.py --force-update --llc-binary=$INSTALL/bin/llc "

echo "Regen called on $1"
TESTCASE="$SOURCE/llvm/test/$1"

echo "Test case $TESTCASE"

if $(grep -Fq 'Assertions have been autogenerated by utils' "$TESTCASE")
then
   echo "Found assertions string"
else
    echo "Unrecognised header"
    exit 1
fi

if $(grep -Fqx '; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --force-update' "$TESTCASE")
then
    echo "Looks like update llc test checks force"
    $UPDATE_LLC_TEST_CHECKS_FORCE $TESTCASE
    exit $?
fi

if $(grep -Fqx '; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py' "$TESTCASE")
then
    echo "Looks like llc_test_checks"
    $UPDATE_LLC_TEST_CHECKS $TESTCASE
    exit $?
fi

if $(grep -Fqx '; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py' "$TESTCASE")
then
    echo "Looks like update mir"
    $UPDATE_MIR $TESTCASE
    exit $?
fi

if $(grep -Fqx '; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --check-globals' "$TESTCASE")
then
    echo "Looks like update test checks function sig / check globals"
    $UPDATE_TEST_CHECKS_FUNCS_GLOBALS $TESTCASE
    exit $?
fi

if $(grep -Fqx '; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: -p --check-globals' "$TESTCASE")
then
    echo "Looks like update test checks p check-globals"
    $UPDATE_TEST_P_CHECKS_GLOBALS $TESTCASE
    exit $?
fi

if $(grep -Fqx '; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: -p --function-signature' "$TESTCASE")
then
    echo "Looks like update test checks p check-funcs"
    $UPDATE_TEST_P_CHECKS_FUNCS $TESTCASE
    exit $?
fi

if $(grep -Fqx '; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: -p --function-signature --include-generated-funcs' "$TESTCASE")
then
    echo "Looks like update test checks p check-all-funcs"
    $UPDATE_TEST_P_CHECKS_ALL_FUNCS $TESTCASE
    exit $?
fi

if $(grep -Fqx '; NOTE: Assertions have been autogenerated by utils/update_test_checks.py' "$TESTCASE")
then
    echo "Looks like update test checks"
    $UPDATE_TEST_CHECKS $TESTCASE
    exit $?
fi

echo "Unknown input, ignoring $TESTCASE"

exit

